"""add_duration_flags_and_formula

Revision ID: 0d9a57576904
Revises: 1f4b0053a3f0
Create Date: 2026-05-11 14:23:21.374586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9a57576904'
down_revision: Union[str, None] = '1f4b0053a3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('per_second', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('per_minute', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('per_hour', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('daily', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('three_days', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('weekly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bi_weekly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('monthly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('yearly', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_entries', schema=None) as batch_op:
        batch_op.drop_column('yearly')
        batch_op.drop_column('monthly')
        batch_op.drop_column('bi_weekly')
        batch_op.drop_column('weekly')
        batch_op.drop_column('three_days')
        batch_op.drop_column('daily')
        batch_op.drop_column('per_hour')
        batch_op.drop_column('per_minute')
        batch_op.drop_column('per_second')
        batch_op.drop_column('formula')

    # ### end Alembic commands ###
