"""add_normalization_to_price_entry

Revision ID: 1f4b0053a3f0
Revises: d805eb26a5ee
Create Date: 2026-05-11 14:03:08.889106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4b0053a3f0'
down_revision: Union[str, None] = 'd805eb26a5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_extracted_records')
    with op.batch_alter_table('extracted_records', schema=None) as batch_op:
        batch_op.alter_column('market',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'local'"))

    with op.batch_alter_table('price_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('normalized_unit', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('comparable_metrics', sa.JSON(), nullable=True))

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.alter_column('market',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'local'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.alter_column('market',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'local'"))

    with op.batch_alter_table('price_entries', schema=None) as batch_op:
        batch_op.drop_column('comparable_metrics')
        batch_op.drop_column('normalized_unit')
        batch_op.drop_column('normalized_value')

    with op.batch_alter_table('extracted_records', schema=None) as batch_op:
        batch_op.alter_column('market',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'local'"))

    op.create_table('_alembic_tmp_extracted_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('snapshot_id', sa.INTEGER(), nullable=False),
    sa.Column('entity_name', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('subcategory', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price_value', sa.FLOAT(), nullable=True),
    sa.Column('price_currency', sa.VARCHAR(), nullable=True),
    sa.Column('billing_period', sa.VARCHAR(), nullable=True),
    sa.Column('unit_value', sa.FLOAT(), nullable=True),
    sa.Column('unit_type', sa.VARCHAR(), nullable=True),
    sa.Column('eligibility', sa.TEXT(), nullable=True),
    sa.Column('effective_date', sa.DATETIME(), nullable=True),
    sa.Column('captured_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('source_url', sa.VARCHAR(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('market', sa.VARCHAR(), server_default=sa.text("'local'"), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['raw_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
