"""add models with import

Revision ID: 34b3af4b618e
Revises: ec123ee583a9
Create Date: 2026-04-17 15:47:20.135055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b3af4b618e'
down_revision: Union[str, None] = 'ec123ee583a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('webhook_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_targets_id'), 'webhook_targets', ['id'], unique=False)
    op.create_table('source_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('page_type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_pages_id'), 'source_pages', ['id'], unique=False)
    op.create_table('raw_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_page_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_snapshots_id'), 'raw_snapshots', ['id'], unique=False)
    op.create_table('extracted_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_value', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(), nullable=True),
    sa.Column('billing_period', sa.String(), nullable=True),
    sa.Column('unit_value', sa.Float(), nullable=True),
    sa.Column('unit_type', sa.String(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['raw_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_records_id'), 'extracted_records', ['id'], unique=False)
    op.create_table('webhook_delivery_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'DEAD_LETTER', name='deliverystatus'), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['extracted_records.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['webhook_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_delivery_attempts_id'), 'webhook_delivery_attempts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_delivery_attempts_id'), table_name='webhook_delivery_attempts')
    op.drop_table('webhook_delivery_attempts')
    op.drop_index(op.f('ix_extracted_records_id'), table_name='extracted_records')
    op.drop_table('extracted_records')
    op.drop_index(op.f('ix_raw_snapshots_id'), table_name='raw_snapshots')
    op.drop_table('raw_snapshots')
    op.drop_index(op.f('ix_source_pages_id'), table_name='source_pages')
    op.drop_table('source_pages')
    op.drop_index(op.f('ix_webhook_targets_id'), table_name='webhook_targets')
    op.drop_table('webhook_targets')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
