"""add_organization_tables

Revision ID: 92005944c227
Revises: 34b3af4b618e
Create Date: 2026-05-08 12:12:09.425070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92005944c227'
down_revision: Union[str, None] = '34b3af4b618e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('emails', sa.Text(), nullable=True),
    sa.Column('phone_numbers', sa.Text(), nullable=True),
    sa.Column('whatsapp_numbers', sa.Text(), nullable=True),
    sa.Column('physical_addresses', sa.Text(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('branches', sa.Text(), nullable=True),
    sa.Column('operating_hours', sa.Text(), nullable=True),
    sa.Column('social_links', sa.Text(), nullable=True),
    sa.Column('registration_status', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('industry_tags', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('executive_leadership', sa.Text(), nullable=True),
    sa.Column('founders', sa.Text(), nullable=True),
    sa.Column('ceo', sa.String(), nullable=True),
    sa.Column('board_members', sa.Text(), nullable=True),
    sa.Column('employee_size', sa.String(), nullable=True),
    sa.Column('revenue_estimate', sa.String(), nullable=True),
    sa.Column('partnerships', sa.Text(), nullable=True),
    sa.Column('competitors', sa.Text(), nullable=True),
    sa.Column('services_offered', sa.Text(), nullable=True),
    sa.Column('products', sa.Text(), nullable=True),
    sa.Column('pricing_notes', sa.Text(), nullable=True),
    sa.Column('customer_reviews', sa.Text(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('seo_metadata', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.Text(), nullable=True),
    sa.Column('hosting_provider', sa.String(), nullable=True),
    sa.Column('analytics_tools', sa.Text(), nullable=True),
    sa.Column('mobile_apps', sa.Text(), nullable=True),
    sa.Column('api_endpoints', sa.Text(), nullable=True),
    sa.Column('traffic_estimate', sa.String(), nullable=True),
    sa.Column('digital_presence_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_profile', sa.Text(), nullable=True),
    sa.Column('sector_classification', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('market_influence_score', sa.Float(), nullable=True),
    sa.Column('innovation_score', sa.Float(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scrape_status', sa.String(), nullable=True),
    sa.Column('scrape_error', sa.Text(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_category'), 'organizations', ['category'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('org_change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('reviewed', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_change_events_change_type'), 'org_change_events', ['change_type'], unique=False)
    op.create_index(op.f('ix_org_change_events_id'), 'org_change_events', ['id'], unique=False)
    op.create_index(op.f('ix_org_change_events_organization_id'), 'org_change_events', ['organization_id'], unique=False)
    # SQLite does not support ALTER COLUMN — skipping type-only changes
    op.create_index(op.f('ix_extracted_records_captured_at'), 'extracted_records', ['captured_at'], unique=False)
    op.create_index(op.f('ix_extracted_records_category'), 'extracted_records', ['category'], unique=False)
    op.create_index(op.f('ix_extracted_records_entity_name'), 'extracted_records', ['entity_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite does not support ALTER COLUMN — skipping type-only changes
    op.drop_index(op.f('ix_extracted_records_entity_name'), table_name='extracted_records')
    op.drop_index(op.f('ix_extracted_records_category'), table_name='extracted_records')
    op.drop_index(op.f('ix_extracted_records_captured_at'), table_name='extracted_records')
    op.drop_index(op.f('ix_org_change_events_organization_id'), table_name='org_change_events')
    op.drop_index(op.f('ix_org_change_events_id'), table_name='org_change_events')
    op.drop_index(op.f('ix_org_change_events_change_type'), table_name='org_change_events')
    op.drop_table('org_change_events')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_category'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
