"""add_organization_catalog_links

Revision ID: d805eb26a5ee
Revises: 92005944c227
Create Date: 2026-05-08 16:16:53.378945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd805eb26a5ee'
down_revision: Union[str, None] = '92005944c227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_records_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_records_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_records_entity_name'), ['entity_name'], unique=False)

    with op.batch_alter_table('price_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_price_entries_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.alter_column('source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_products_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.alter_column('source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_services_organization_id', 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('fk_services_organization_id', type_='foreignkey')
        batch_op.alter_column('source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_organization_id', type_='foreignkey')
        batch_op.alter_column('source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('price_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_price_entries_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('extracted_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_records_entity_name'))
        batch_op.drop_index(batch_op.f('ix_extracted_records_category'))
        batch_op.drop_index(batch_op.f('ix_extracted_records_captured_at'))
        batch_op.drop_index(batch_op.f('ix_extracted_records_captured_at'))

    # ### end Alembic commands ###
